#!/usr/local/bin/node
/**
 * Runs a simple dev server on localhost:4000 for previewing LESS styles.
 */
var express = require('express');
var app = express();
app.use(express.static(__dirname));
app.listen(4000, function() { console.log('Listening at http://localhost:4000'); });